// ── Chart of Accounts (COA) — from GWR COA.xlsx ──

export interface CoaAccount {
  code: string;
  name: string;
  type: string;
}

export const CHART_OF_ACCOUNTS: CoaAccount[] = [
  { code: '1000', name: 'Turnover', type: 'Income' },
  { code: '10000', name: 'Equity and reserves', type: 'Equity' },
  { code: '100001', name: 'Share capital', type: 'Equity' },
  { code: '100002', name: 'Retained earnings', type: 'Equity' },
  { code: '100003', name: 'Profit or loss for the year', type: 'Equity' },
  { code: '100004', name: 'Dividend paid', type: 'Current Year Earnings' },
  { code: '10001', name: 'Direct sales', type: 'Income' },
  { code: '10002', name: 'Tour operator', type: 'Income' },
  { code: '10003', name: 'Indirect sales', type: 'Income' },
  { code: '11000', name: 'Non current liabilities', type: 'Non-current Liabilities' },
  { code: '1100001', name: 'Lease liabilities', type: 'Non-current Liabilities' },
  { code: '1100002', name: 'Bank borrowings', type: 'Non-current Liabilities' },
  { code: '110100', name: 'Stock Valuation', type: 'Current Assets' },
  { code: '110200', name: 'Stock Interim (Received)', type: 'Current Assets' },
  { code: '110300', name: 'Stock Interim (Delivered)', type: 'Current Assets' },
  { code: '110301', name: 'Inventory fish', type: 'Current Assets' },
  { code: '110302', name: 'Inventory chicken', type: 'Current Assets' },
  { code: '110303', name: 'Inventory lobster 500G', type: 'Current Assets' },
  { code: '110304', name: 'Inventory lobster 200G', type: 'Current Assets' },
  { code: '110305', name: 'Inventory lobster 400G', type: 'Current Assets' },
  { code: '110306', name: 'Inventory gambass 100G', type: 'Current Assets' },
  { code: '110307', name: 'Inventory Rhum Bottle', type: 'Current Assets' },
  { code: '110308', name: 'Inventory wine white Bottle', type: 'Current Assets' },
  { code: '110309', name: 'Inventory wine rosé Bottle', type: 'Current Assets' },
  { code: '110310', name: 'Inventory beer bottle', type: 'Current Assets' },
  { code: '110311', name: 'Inventory coca bottle', type: 'Current Assets' },
  { code: '110400', name: 'Cost of Production', type: 'Current Assets' },
  { code: '12000', name: 'Current liabilities', type: 'Current Liabilities' },
  { code: '1200001', name: 'Trade and other payables', type: 'Current Liabilities' },
  { code: '1200002', name: 'Lease liabilities', type: 'Current Liabilities' },
  { code: '1200003', name: 'Bank borrowings', type: 'Current Liabilities' },
  { code: '1200004', name: 'Vat liabilities', type: 'Current Liabilities' },
  { code: '1200005', name: 'TDS liabilities', type: 'Current Liabilities' },
  { code: '1200006', name: 'Current tax liabilities', type: 'Current Liabilities' },
  { code: '121000', name: 'Account Receivable', type: 'Receivable' },
  { code: '122O00', name: 'Account Receivable (PoS)', type: 'Receivable' },
  { code: '123000', name: 'Products to receive', type: 'Current Assets' },
  { code: '131000', name: 'Tax Paid', type: 'Current Assets' },
  { code: '132000', name: 'Tax Receivable', type: 'Current Assets' },
  { code: '141000', name: 'Prepayments', type: 'Prepayments' },
  { code: '151000', name: 'Fixed Asset', type: 'Fixed Assets' },
  { code: '191000', name: 'Non-current assets', type: 'Non-current Assets' },
  { code: '2000', name: 'Cost of sales', type: 'Expenses' },
  { code: '20001', name: 'Release of inventory', type: 'Expenses' },
  { code: '20002', name: 'Other purchase materials', type: 'Expenses' },
  { code: '200024', name: 'Indirect labour', type: 'Expenses' },
  { code: '20003', name: 'Direct labour costs', type: 'Expenses' },
  { code: '211000', name: 'Account Payable', type: 'Payable' },
  { code: '211100', name: 'Bills to receive', type: 'Current Liabilities' },
  { code: '230000', name: 'Salary Payable', type: 'Current Liabilities' },
  { code: '230001', name: 'Bank', type: 'Bank and Cash' },
  { code: '230002', name: 'Bank Suspense Account', type: 'Current Assets' },
  { code: '230100', name: 'Employee Payroll Taxes', type: 'Current Liabilities' },
  { code: '230200', name: 'Employer Payroll Taxes', type: 'Current Liabilities' },
  { code: '231001', name: 'Cash', type: 'Bank and Cash' },
  { code: '232001', name: 'Liquidity Transfer', type: 'Current Assets' },
  { code: '251000', name: 'VAT Received', type: 'Current Liabilities' },
  { code: '252000', name: 'Tax Payable', type: 'Current Liabilities' },
  { code: '3000', name: 'Other expenses', type: 'Expenses' },
  { code: '30001', name: 'Administrative expenses', type: 'Expenses' },
  { code: '30002', name: 'Bank charges', type: 'Expenses' },
  { code: '30003', name: 'Professional fees', type: 'Expenses' },
  { code: '30004', name: 'Repairs and maintenance', type: 'Expenses' },
  { code: '30005', name: 'IT fees', type: 'Expenses' },
  { code: '30006', name: 'Company licence', type: 'Expenses' },
  { code: '30007', name: 'Trade licence', type: 'Expenses' },
  { code: '30008', name: 'Tourism Authority', type: 'Expenses' },
  { code: '30009', name: 'MRA licence', type: 'Expenses' },
  { code: '30010', name: 'Other licence', type: 'Expenses' },
  { code: '30011', name: 'Boat insurance', type: 'Expenses' },
  { code: '30012', name: 'Motor car insurance', type: 'Expenses' },
  { code: '30013', name: 'Other insurance', type: 'Expenses' },
  { code: '301000', name: 'Capital', type: 'Equity' },
  { code: '302000', name: 'Dividends', type: 'Equity' },
  { code: '4000', name: 'Payroll costs admin', type: 'Expenses' },
  { code: '400000', name: 'Product Sales', type: 'Income' },
  { code: '40001', name: 'Basic salary', type: 'Expenses' },
  { code: '40002', name: 'CSG', type: 'Expenses' },
  { code: '40003', name: 'Other payroll costs', type: 'Expenses' },
  { code: '40004', name: 'Transport allowance', type: 'Expenses' },
  { code: '40005', name: 'Fuel', type: 'Expenses' },
  { code: '40006', name: 'Training', type: 'Expenses' },
  { code: '40007', name: 'Staff entertainment', type: 'Expenses' },
  { code: '441000', name: 'Foreign Exchange Gain', type: 'Income' },
  { code: '442000', name: 'Cash Difference Gain', type: 'Income' },
  { code: '443000', name: 'Cash Discount Loss', type: 'Expenses' },
  { code: '450000', name: 'Other Income', type: 'Other Income' },
  { code: '5000', name: 'Finance cost', type: 'Expenses' },
  { code: '500000', name: 'Cost of Goods Sold', type: 'Cost of Revenue' },
  { code: '50001', name: 'Interest on loan', type: 'Expenses' },
  { code: '50002', name: 'Interest on lease', type: 'Expenses' },
  { code: '50003', name: 'Other interest', type: 'Expenses' },
  { code: '6000', name: 'Depreciation charge', type: 'Expenses' },
  { code: '600000', name: 'Expenses', type: 'Expenses' },
  { code: '611000', name: 'Purchase of Equipments', type: 'Expenses' },
  { code: '612000', name: 'Rent', type: 'Expenses' },
  { code: '620000', name: 'Bank Fees', type: 'Expenses' },
  { code: '630000', name: 'Salary Expenses', type: 'Expenses' },
  { code: '641000', name: 'Foreign Exchange Loss', type: 'Expenses' },
  { code: '642000', name: 'Cash Difference Loss', type: 'Expenses' },
  { code: '643000', name: 'Cash Discount Gain', type: 'Income' },
  { code: '7000', name: 'Taxation', type: 'Expenses' },
  { code: '70001', name: 'Income tax', type: 'Expenses' },
  { code: '70002', name: 'CSR', type: 'Expenses' },
  { code: '70003', name: 'CCL', type: 'Expenses' },
  { code: '8000', name: 'Property, plant and equipment', type: 'Non-current Assets' },
  { code: '80001', name: 'Boat cost', type: 'Non-current Assets' },
  { code: '80002', name: 'Boat accumulated depreciation', type: 'Non-current Assets' },
  { code: '80003', name: 'Motor car cost', type: 'Non-current Assets' },
  { code: '80004', name: 'Motor car accumulated depreciation', type: 'Non-current Assets' },
  { code: '80005', name: 'Computer equipment cost', type: 'Non-current Assets' },
  { code: '80006', name: 'Computer equipment accumulated depreciation', type: 'Non-current Assets' },
  { code: '9000', name: 'Current assets', type: 'Current Assets' },
  { code: '900012', name: 'Stock of chicken', type: 'Current Assets' },
  { code: '900013', name: 'Stock of langouste', type: 'Current Assets' },
  { code: '900014', name: 'Stock of fish', type: 'Current Assets' },
  { code: '900015', name: 'Stock of beer bottle', type: 'Current Assets' },
  { code: '900016', name: 'Stock of beer Chopine', type: 'Current Assets' },
  { code: '900017', name: 'Stock of coca cola', type: 'Current Assets' },
  { code: '900018', name: 'Stock of sprite', type: 'Current Assets' },
  { code: '900019', name: 'Stock of rhum', type: 'Current Assets' },
  { code: '900041', name: 'Absa MUR', type: 'Current Assets' },
  { code: '900042', name: 'Absa EUR', type: 'Current Assets' },
  { code: '900043', name: 'Absa USD', type: 'Current Assets' },
  { code: '900044', name: 'Absa GBP', type: 'Current Assets' },
  { code: '9001', name: 'Inventory', type: 'Current Assets' },
  { code: '9002', name: 'Trade and other receivables', type: 'Current Assets' },
  { code: '9003', name: 'Cash in hand', type: 'Current Assets' },
  { code: '9004', name: 'Cash at bank', type: 'Current Assets' },
  { code: '9005', name: 'Vat recoverable', type: 'Current Assets' },
  { code: '9006', name: 'Salary control account', type: 'Current Assets' },
  { code: '961000', name: 'RD Expenses', type: 'Expenses' },
  { code: '962000', name: 'Sales Expenses', type: 'Expenses' },
];

// ── Lookup map: code → CoaAccount ──

export const COA_MAP: Record<string, CoaAccount> = Object.fromEntries(
  CHART_OF_ACCOUNTS.map((a) => [a.code, a])
);

// ── Helper: get account display name for a code ──

export function getAccountLabel(code: string): string {
  return COA_MAP[code]?.name ?? '';
}
